apiVersion: v1
kind: Secret
metadata:
  name: my-python-app-secrets
type: Opaque
data:
  DBHOST: "MTAuOTYuMy4yMDE="  # Base64 encoded value of 10.96.114.178
  DBPORT: "MzMwNg=="              # Base64 encoded value of 3306
  DBUSER: "cm9vdA=="              # Base64 encoded value of root
  DATABASE: "ZW1wbG95ZWVz"        # Base64 encoded value of employees
  DBPWD: "cGFzc3dvcmQ="          # Base64 encoded value of password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-python-app-config
data:
  APP_COLOR: "blue"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: 349484560216.dkr.ecr.us-east-1.amazonaws.com/my-python-app-v2:latest
        env:
        - name: DBHOST
          valueFrom:
            secretKeyRef:
              name: my-python-app-secrets
              key: DBHOST
        - name: DBPORT
          valueFrom:
            secretKeyRef:
              name: my-python-app-secrets
              key: DBPORT
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: my-python-app-secrets
              key: DBUSER
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: my-python-app-secrets
              key: DATABASE
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: my-python-app-secrets
              key: DBPWD
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: my-python-app-config
              key: APP_COLOR
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: my-python-app
